### ISSUE TITLE
预训练命令传参错误

### ISSUE THREAD

**Issue by TediousBoredom** [xiaojino/TWA#1]
`问题一、
`# from numpy.lib.financial import _ipmt_dispatcher`
`ModuleNotFoundError: No module named 'numpy.lib.financial'`
![image](https://github.com/xiaojino/TWA/assets/111668189/68d09211-0869-4459-b1d7-636d376b7b6d)
<img width="973" alt="image" src="https://github.com/xiaojino/TWA/assets/111668189/73432619-c379-44a7-bf15-f692ebc790fc">

注释后解决

问题二、传参错误
raise subprocess.CalledProcessError(returncode=process.returncode,
`subprocess.CalledProcessError: Command '['/home/dell/anaconda3/envs/twa/bin/python', '-u', 'tools/run.py', '--local_rank=3', '--pretrain', '--tasks', 'vqa', '--datasets', 'm4c_textvqa', '--model', 'twa', '--seed', '13', '--config', 'configs/vqa/m4c_textvqa/twa_pretrain.yml', '--save_dir', 'save/twa_pretrain_test', 'training_parameters.distributed', 'True']' returned non-zero exit status 1.`
<img width="681" alt="image" src="https://github.com/xiaojino/TWA/assets/111668189/181a9573-7a5c-44cb-aa9b-14aa08d5d866">
<img width="676" alt="image" src="https://github.com/xiaojino/TWA/assets/111668189/ead9e407-0692-472d-a0e4-f13319ac6fa7">

像是传参问题，通过把命令
`“python -m torch.distributed.launch --nproc_per_node 4 tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model twa --seed 13 --config configs/vqa/m4c_textvqa/twa_pretrain.yml --save_dir save/twa_pretrain_test training_parameters.distributed True”`
中的“-m torch.distributed.launch --nproc_per_node 4”删除，只运行

`“python tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model twa --seed 13 --config configs/vqa/m4c_textvqa/twa_pretrain.yml --save_dir save/twa_pretrain_test training_parameters.distributed True”`

问题得到解决`
请问这种解决方式是否会有其他问题，是否会导致其他错误产生
![image](https://github.com/xiaojino/TWA/assets/111668189/4e01ce77-1824-462e-a223-9fd70f859514)

问题三、[bert-base-uncased](https://huggingface.co/bert-base-uncased)
Model name 'data/bert-base-uncased' was not found in model name list
`bert_tokenizer = BertTokenizer.from_pretrained('data/bert-base-uncased')`
<img width="839" alt="image" src="https://github.com/xiaojino/TWA/assets/111668189/d2417bc6-3791-4688-99dd-6719b68ff3fe">
<img width="679" alt="image" src="https://github.com/xiaojino/TWA/assets/111668189/d11d08a9-6065-4f23-a3c4-41798c58f5cd">

通过把项目中所有用到[bert-base-uncased](https://huggingface.co/bert-base-uncased)的地方把前面的data/删除
即
`bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')`每次运行从官网下载
或者从网上下载放入data文件夹得到解决，
请问这种解决方式是否会导致其他错误
问题四、数据集需要全部（62G）完成后才能预训练吗？
在前三个问题解决后，下载了四十多G的数据然后运行预训练命令
/home/dell/桌面/TWA/pythia/../data/feat_resx/train/ -name "c8f22611ac739c5a.npy.npy"未找到这个数据文件
FileFoundError,
请问需要把全部62G的数据全部下载完才能进行预训练吗？

**Comment by Allfather9** [comment]
我通过删除一部分的参数实现正常运行，但感觉不妥当。
请问预训练的命令传参问题该怎么正确解决？
