### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/桌面/TWA/pythia/../data/feat_resx/train/c8f22611ac739c5a.npy'

### ISSUE THREAD

**Issue by TediousBoredom** [xiaojino/TWA#2]
在INFO: Starting training...这个阶段
ERROR: Caught FileNotFoundError in DataLoader worker process 0.
after use this command to pretrain, it raise this error
`python tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model twa --seed 13 --config configs/vqa/m4c_textvqa/twa_pretrain.yml --save_dir save/twa_pretrain_test training_parameters.distributed True
`
why it raise this error?how to solve this error?

**Comment by xiaojino** [comment]
“FileNotFoundError”
Maybe you need to check if any files in the data folder are missing or if the folder location has changed

**Comment by xiaojino** [comment]
Please refer to the Readme in the data folder  to download the data.

**Comment by Allfather9** [comment]
I have referred to the Readme in the data folder to download the data.
when download the data, I run this command
`azcopy copy https://tapvqacaption.blob.core.windows.net/data/data ./ --recursive`
and download about 100G data.
![image](https://github.com/xiaojino/TWA/assets/111668189/a5a7a357-b494-406d-9445-c7880c3ed290)

![image](https://github.com/xiaojino/TWA/assets/111668189/8bc5c417-d6fa-4b0d-9e4a-b3d03b86f7aa)

**Comment by Allfather9** [comment]
> Please refer to the Readme in the data folder to download the data.
every time I run the download command again, it will show this. 
![image](https://github.com/xiaojino/TWA/assets/111668189/9ca4e01e-aec2-4e65-836c-fb846eabd9f9)

I have referred to the Readme in the data folder to download the data.
when download the data, I run this command
`azcopy copy https://tapvqacaption.blob.core.windows.net/data/data ./ --recursive`
and download about 100G data.
![image](https://github.com/xiaojino/TWA/assets/111668189/a5a7a357-b494-406d-9445-c7880c3ed290)

![image](https://github.com/xiaojino/TWA/assets/111668189/8bc5c417-d6fa-4b0d-9e4a-b3d03b86f7aa)

**Comment by Allfather9** [comment]
thank you for reply!

but every time I run the download command again, it will show this.



I have referred to the Readme in the data folder to download the data.

when download the data, I run this command

azcopy copy https://tapvqacaption.blob.core.windows.net/data/data ./ --recursive

and download about 100G data.





I think I have download enough data but it still raise this FileNotFoundError.



                       
原始邮件
                       
                     

发件人："xiaojino"< ***@***.*** &gt;;

发件时间：2023/8/1 17:34

收件人："xiaojino/TWA"< ***@***.*** &gt;;

抄送人："Allfather9"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [xiaojino/TWA] FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/桌面/TWA/pythia/../data/feat_resx/train/c8f22611ac739c5a.npy' (Issue #2)




 
Please refer to the Readme in the data folder  to download the data.
